version: '3.1'
services:

  php:
    env_file:
      - .env
    build:
      context: ./php
      dockerfile: ${PHP_DOCKER_VERSION}
    expose:
      - ${PHP_FPM_PORT}
    volumes:
      - ./php/${PHP_DOCKER_VERSION}.ini:/usr/local/etc/php/conf.d/${PHP_DOCKER_VERSION}.ini
      - ${SOURCE_CODE}:/var/www/
    container_name: php
    restart: always

  nginx:
    build: ./nginx
    ports:
      - ${HOST_IP}:80:80
      - ${HOST_IP}:443:443
    depends_on:
      - php
    volumes:
      - ./nginx/ssl:/etc/ssl/
      - ${SOURCE_CODE}:/var/www/
    container_name: nginx
    restart: always

  mysql:
    build: ./mysql
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    container_name: mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${HOST_IP}:8080:80
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
    container_name: phpmyadmin
    restart: always

volumes:
  mysql:
    driver: "local"
    #driver: /var/lib/docker/volumes/docker_mysql/_data/mysql
