version: '2'
services:
    applications:
        image: busybox:latest
        volumes:
            - ./src:/var/www/html
    php-fpm:
        env_file:
            - .env
        build:
            context: ./php-fpm
            args:
                - INSTALL_GD=${INSTALL_GD}
                - INSTALL_PDO=${INSTALL_PDO}
            dockerfile: Dockerfile
        expose:
            - 9000
        volumes_from:
            - applications
    nginx:
        build: ./nginx
        ports:
            - ${HOST_IP}:80:80
        depends_on:
            - php-fpm
        volumes_from:
            - applications
        extra_hosts:
            - "webhost:${HOST_IP}" # Append webhost to /etc/hosts
    mysql:
        image: mysql:latest
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
volumes:
    mysql:
        driver: "local"
