version: '3'
services:

  php:
    env_file:
      - .env
    build:
      context: ./php
      dockerfile: ${PHP_DOCKER_VERSION}
    expose:
      - ${PHP_FPM_PORT}
    volumes:
      - ./php/${PHP_DOCKER_VERSION}.ini:/usr/local/etc/php/conf.d/${PHP_DOCKER_VERSION}.ini
      - ${SOURCE_CODE}:/var/www/
    #container_name: php

  nginx:
    build: ./nginx
    ports:
      - ${HOST_IP}:80:80
      - ${HOST_IP}:443:443
    depends_on:
      - php
    volumes:
      - ./nginx/ssl:/etc/ssl/
      - ${SOURCE_CODE}:/var/www/
    #container_name: nginx

  mysql:
    build: ./mysql
    volumes:
      - ./scripts/:/scripts
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    #container_name: mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${HOST_IP}:8080:80
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
    #container_name: phpmyadmin

volumes:
  mysql:
    driver: "local" #/var/lib/docker/volumes/docker_mysql/_data/mysql
