version: '2'
services:

    application:
        image: busybox:latest
        volumes:
            - ${SOURCE_CODE}:/var/www/html

    php:
        env_file:
            - .env
        build:
            context: ./php
            dockerfile: ${PHP_DOCKER_VERSION}
        expose:
            - ${PHP_FPM_PORT}
        volumes_from:
            - application

    nginx:
        build: ./nginx
        ports:
            - ${HOST_IP}:80:80
        depends_on:
            - php
        volumes_from:
            - application

    mysql:
        image: mariadb:latest
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - ${HOST_IP}:8080:80
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
volumes:
    mysql:
        driver: "local"
