apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  volumes:
    - name: storage-name
      persistentVolumeClaim:
        claimName: pv0001-claim
  containers:
    - name: ubuntu
      image: docker_php:latest
      command:
        - sleep
        - "infinity"
      volumeMounts:
        - mountPath: "/storage"
          name: storage-name
      imagePullPolicy: Never
